# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 437)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_ = QtWidgets.QLabel(self.centralwidget)
        self.label_.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_.setFont(font)
        self.label_.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                  "color: rgb(0, 0, 255);\n"
                                  "background-color: rgb(85, 255, 255);\n"
                                  "color: rgb(255, 0, 0);")
        self.label_.setObjectName("label_")
        self.obj0 = QtWidgets.QPushButton(self.centralwidget)
        self.obj0.setGeometry(QtCore.QRect(0, 250, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj0.setFont(font)
        self.obj0.setStyleSheet("background-color: rgb(255, 85, 255);")
        self.obj0.setObjectName("obj0")
        self.obj_equal = QtWidgets.QPushButton(self.centralwidget)
        self.obj_equal.setGeometry(QtCore.QRect(150, 250, 150, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_equal.setFont(font)
        self.obj_equal.setStyleSheet("background-color: rgb(255, 85, 255);\n"
                                     "background-color: rgb(170, 255, 127);")
        self.obj_equal.setObjectName("obj_equal")
        self.obj7 = QtWidgets.QPushButton(self.centralwidget)
        self.obj7.setGeometry(QtCore.QRect(0, 190, 101, 61))
        self.obj7.setObjectName("obj7")
        self.obj8 = QtWidgets.QPushButton(self.centralwidget)
        self.obj8.setGeometry(QtCore.QRect(100, 190, 101, 61))
        self.obj8.setObjectName("obj8")
        self.obj9 = QtWidgets.QPushButton(self.centralwidget)
        self.obj9.setGeometry(QtCore.QRect(200, 190, 101, 61))
        self.obj9.setObjectName("obj9")
        self.obj4 = QtWidgets.QPushButton(self.centralwidget)
        self.obj4.setGeometry(QtCore.QRect(0, 130, 101, 61))
        self.obj4.setObjectName("obj4")
        self.obj5 = QtWidgets.QPushButton(self.centralwidget)
        self.obj5.setGeometry(QtCore.QRect(100, 130, 101, 61))
        self.obj5.setObjectName("obj5")
        self.obj6 = QtWidgets.QPushButton(self.centralwidget)
        self.obj6.setGeometry(QtCore.QRect(200, 130, 101, 61))
        self.obj6.setObjectName("obj6")
        self.obj3 = QtWidgets.QPushButton(self.centralwidget)
        self.obj3.setGeometry(QtCore.QRect(200, 70, 101, 61))
        self.obj3.setObjectName("obj3")
        self.obj2 = QtWidgets.QPushButton(self.centralwidget)
        self.obj2.setGeometry(QtCore.QRect(100, 70, 101, 61))
        self.obj2.setObjectName("obj2")
        self.obj1 = QtWidgets.QPushButton(self.centralwidget)
        self.obj1.setGeometry(QtCore.QRect(0, 70, 101, 61))
        self.obj1.setObjectName("obj1")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 190, 93, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 130, 93, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 70, 93, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 250, 91, 81))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)




        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_function()

        self.is_equal=False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_.setText(_translate("MainWindow", "0"))
        self.obj0.setText(_translate("MainWindow", "0"))
        self.obj_equal.setText(_translate("MainWindow", "="))
        self.obj7.setText(_translate("MainWindow", "7"))
        self.obj8.setText(_translate("MainWindow", "8"))
        self.obj9.setText(_translate("MainWindow", "9"))
        self.obj4.setText(_translate("MainWindow", "4"))
        self.obj5.setText(_translate("MainWindow", "5"))
        self.obj6.setText(_translate("MainWindow", "6"))
        self.obj3.setText(_translate("MainWindow", "3"))
        self.obj2.setText(_translate("MainWindow", "2"))
        self.obj1.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "*"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.pushButton_3.setText(_translate("MainWindow", "+"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))

    def add_function(self):
        self.obj0.clicked.connect(lambda: self.write_number(self.obj0.text()))
        self.obj1.clicked.connect(lambda: self.write_number(self.obj1.text()))
        self.obj2.clicked.connect(lambda: self.write_number(self.obj2.text()))
        self.obj3.clicked.connect(lambda: self.write_number(self.obj3.text()))
        self.obj4.clicked.connect(lambda: self.write_number(self.obj4.text()))
        self.obj5.clicked.connect(lambda: self.write_number(self.obj5.text()))
        self.obj6.clicked.connect(lambda: self.write_number(self.obj6.text()))
        self.obj7.clicked.connect(lambda: self.write_number(self.obj7.text()))
        self.obj8.clicked.connect(lambda: self.write_number(self.obj8.text()))
        self.obj9.clicked.connect(lambda: self.write_number(self.obj9.text()))
        self.pushButton.clicked.connect(lambda: self.write_number(self.pushButton.text()))
        self.pushButton_2.clicked.connect(lambda: self.write_number(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write_number(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write_number(self.pushButton_4.text()))
        self.obj_equal.clicked.connect(self.results)

    def write_number(self, number):
        if self.label_.text() == '0' or self.is_equal==True:
            self.label_.setText(number)
            self.is_equal=False

        else:
            self.label_.setText(self.label_.text() + number)

    def results(self):
        try:
            res = eval(self.label_.text())
            self.label_.setText("Результат:" + str(res))
            self.is_equal=True
        except ZeroDivisionError:
            self.label_.setText("На ноль делить нельзя" )
            self.is_equal = True


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
